version: "2"

services:
  nginx_ssl:
    image: linuxserver/letsencrypt
    container_name: nginx_ssl
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - URL=needon.kr #수정
      - SUBDOMAINS=www, #수정
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #수정
      - EMAIL=admin@needon.kr #수정
      - DHLEVEL=2048
      - STAGING=false
    links:
      - "php"
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
  
  php:
    container_name: php
    build: ./config/php
    volumes:
      - <"웹파일 저장위치">:/var/www/html #수정
      - "./config/php/apache-remoteip.conf:/etc/apache2/mods-enabled/remoteip.conf:ro"