version: "2"

services:
  mariadb:
    container_name: mariadb
    build: .
    environment:
        - MYSQL_ROOT_PASSWORD = 1234 #수정
        - TZ=Asia/Seoul
    restart: always
    ports:
        - "3306:3306"
    volumes:
      - "../../config/mariadb/conf.d/config.cnf:/etc/mysql/conf.d/config.cnf"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    container_name: phpmyadmin
    image: ebspace/armhf-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    links:
      - "mariadb:db"
    environment:
      - PMA_HOST = "needon.kr" #수정